# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from Custom_Widgets.Widgets import QCustomSlideMenu
from mplwidget import MplWidget
from mpldiagramma import MplDiagramma

import resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1366, 768)
        MainWindow.setMinimumSize(QSize(1366, 768))
        MainWindow.setMaximumSize(QSize(1366, 768))
        icon = QIcon()
        icon.addFile(u":/resource/icons/icons8-monitor-60.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"*{\n"
"	border: none;\n"
"	background-color: transparent;\n"
"	color: #fff;\n"
"}\n"
"#centralwidget{\n"
"	background-color: #E0E0E0;\n"
"}\n"
"#side_menu{\n"
"	background-color: #F5F5F5;\n"
"	background-color: transparent;\n"
"\n"
"	border-radius: 20px;\n"
"}\n"
"#QPushButton{\n"
"	padding: 10px;\n"
"	background-color: #EAFBFF;\n"
"	border-radius: 5px;\n"
"}\n"
"#main_body{\n"
"	background-color: #EEEEEE;\n"
"	border-radius: 10px;\n"
"}\n"
"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.header = QFrame(self.centralwidget)
        self.header.setObjectName(u"header")
        self.header.setMinimumSize(QSize(0, 70))
        self.header.setMaximumSize(QSize(16777215, 50))
        self.header.setFrameShape(QFrame.StyledPanel)
        self.header.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.header)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.header)
        self.frame.setObjectName(u"frame")
        self.frame.setMinimumSize(QSize(50, 50))
        self.frame.setMaximumSize(QSize(50, 50))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.frame)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.menu_btn = QPushButton(self.frame)
        self.menu_btn.setObjectName(u"menu_btn")
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn.sizePolicy().hasHeightForWidth())
        self.menu_btn.setSizePolicy(sizePolicy)
        self.menu_btn.setMinimumSize(QSize(50, 50))
        self.menu_btn.setMaximumSize(QSize(150, 50))
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.menu_btn.setFont(font)
        self.menu_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.menu_btn.setStyleSheet(u"background-image:url(:/resource/icons/icons8-\u043c\u0435\u043d\u044e-\u0432-\u043a\u0432\u0430\u0434\u0440\u0430\u0442\u0435-50.png)")
        icon1 = QIcon()
        icon1.addFile(u":/resource/icons/icons8-\u043c\u0435\u043d\u044e-50.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_btn.setIcon(icon1)
        self.menu_btn.setIconSize(QSize(25, 25))

        self.horizontalLayout_4.addWidget(self.menu_btn)


        self.horizontalLayout_2.addWidget(self.frame)

        self.frame_3 = QFrame(self.header)
        self.frame_3.setObjectName(u"frame_3")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy1)
        self.frame_3.setMinimumSize(QSize(0, 0))
        self.frame_3.setMaximumSize(QSize(16777215, 16777215))
        font1 = QFont()
        font1.setBold(False)
        self.frame_3.setFont(font1)
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.getstat = QLabel(self.frame_3)
        self.getstat.setObjectName(u"getstat")
        font2 = QFont()
        font2.setPointSize(16)
        font2.setBold(True)
        self.getstat.setFont(font2)
        self.getstat.setStyleSheet(u"color: #000;")
        self.getstat.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_3.addWidget(self.getstat)


        self.horizontalLayout_2.addWidget(self.frame_3)


        self.verticalLayout.addWidget(self.header)

        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy2)
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.side_menu = QCustomSlideMenu(self.frame_2)
        self.side_menu.setObjectName(u"side_menu")
        self.side_menu.setMinimumSize(QSize(0, 656))
        self.side_menu.setMaximumSize(QSize(16777215, 16777215))
        self.side_menu.setStyleSheet(u"background-color: #F5F5F5;\n"
"	border-radius: 20px;")
        self.verticalLayout_2 = QVBoxLayout(self.side_menu)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 300)
        self.frame_4 = QFrame(self.side_menu)
        self.frame_4.setObjectName(u"frame_4")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy3)
        self.frame_4.setMinimumSize(QSize(150, 300))
        self.frame_4.setMaximumSize(QSize(150, 300))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setSpacing(9)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.frame_36 = QFrame(self.frame_4)
        self.frame_36.setObjectName(u"frame_36")
        self.frame_36.setMaximumSize(QSize(16777215, 75))
        self.frame_36.setFrameShape(QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_19 = QHBoxLayout(self.frame_36)
        self.horizontalLayout_19.setObjectName(u"horizontalLayout_19")
        self.frame_37 = QFrame(self.frame_36)
        self.frame_37.setObjectName(u"frame_37")
        self.frame_37.setMinimumSize(QSize(50, 50))
        self.frame_37.setMaximumSize(QSize(50, 50))
        self.frame_37.setStyleSheet(u"background-image:url(:/resource/icons/icons8-\u0433\u043b\u0430\u0432\u043d\u0430\u044f-\u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430-50.png)")
        self.frame_37.setFrameShape(QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_19.addWidget(self.frame_37)

        self.getstat_btn = QPushButton(self.frame_36)
        self.getstat_btn.setObjectName(u"getstat_btn")
        self.getstat_btn.setMinimumSize(QSize(0, 50))
        self.getstat_btn.setMaximumSize(QSize(16777215, 50))
        font3 = QFont()
        font3.setPointSize(13)
        font3.setBold(True)
        self.getstat_btn.setFont(font3)
        self.getstat_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.getstat_btn.setStyleSheet(u"color: #000000;")
        self.getstat_btn.setIcon(icon)
        self.getstat_btn.setIconSize(QSize(30, 30))

        self.horizontalLayout_19.addWidget(self.getstat_btn)


        self.verticalLayout_3.addWidget(self.frame_36)

        self.frame_34 = QFrame(self.frame_4)
        self.frame_34.setObjectName(u"frame_34")
        self.frame_34.setMaximumSize(QSize(16777215, 75))
        self.frame_34.setFrameShape(QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_18 = QHBoxLayout(self.frame_34)
        self.horizontalLayout_18.setObjectName(u"horizontalLayout_18")
        self.frame_35 = QFrame(self.frame_34)
        self.frame_35.setObjectName(u"frame_35")
        self.frame_35.setMinimumSize(QSize(50, 50))
        self.frame_35.setMaximumSize(QSize(50, 50))
        self.frame_35.setStyleSheet(u"background-image:url(:/resource/icons/icons8-\u0434\u0438\u0430\u0433\u0440\u0430\u043c\u043c\u0430-\u0441-\u043e\u0431\u043b\u0430\u0441\u0442\u044f\u043c\u0438-50.png)")
        self.frame_35.setFrameShape(QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_18.addWidget(self.frame_35)

        self.analyse_btn = QPushButton(self.frame_34)
        self.analyse_btn.setObjectName(u"analyse_btn")
        self.analyse_btn.setMinimumSize(QSize(0, 50))
        self.analyse_btn.setMaximumSize(QSize(16777215, 50))
        font4 = QFont()
        font4.setBold(True)
        self.analyse_btn.setFont(font4)
        self.analyse_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.analyse_btn.setLayoutDirection(Qt.LeftToRight)
        self.analyse_btn.setStyleSheet(u"color: #000000;")
        icon2 = QIcon()
        icon2.addFile(u":/resource/icons/icons8-\u043a\u043e\u043c\u0431\u0438\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439-\u0433\u0440\u0430\u0444\u0438\u043a-50.png", QSize(), QIcon.Normal, QIcon.Off)
        self.analyse_btn.setIcon(icon2)
        self.analyse_btn.setIconSize(QSize(25, 25))

        self.horizontalLayout_18.addWidget(self.analyse_btn)


        self.verticalLayout_3.addWidget(self.frame_34)

        self.frame_32 = QFrame(self.frame_4)
        self.frame_32.setObjectName(u"frame_32")
        self.frame_32.setMaximumSize(QSize(16777215, 75))
        self.frame_32.setFrameShape(QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_17 = QHBoxLayout(self.frame_32)
        self.horizontalLayout_17.setObjectName(u"horizontalLayout_17")
        self.frame_33 = QFrame(self.frame_32)
        self.frame_33.setObjectName(u"frame_33")
        self.frame_33.setMaximumSize(QSize(50, 50))
        self.frame_33.setStyleSheet(u"background-image:url(:/resource/icons/icons8-\u043f\u043e\u043c\u043e\u0449\u044c-50.png)")
        self.frame_33.setFrameShape(QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_17.addWidget(self.frame_33)

        self.about_btn = QPushButton(self.frame_32)
        self.about_btn.setObjectName(u"about_btn")
        self.about_btn.setMinimumSize(QSize(0, 50))
        self.about_btn.setMaximumSize(QSize(16777215, 50))
        self.about_btn.setFont(font4)
        self.about_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.about_btn.setStyleSheet(u"color: #000000;")
        icon3 = QIcon()
        icon3.addFile(u":/resource/icons/icons8-\u0437\u0430\u0434\u0430\u0442\u044c-\u0432\u043e\u043f\u0440\u043e\u0441-50.png", QSize(), QIcon.Normal, QIcon.Off)
        self.about_btn.setIcon(icon3)
        self.about_btn.setIconSize(QSize(25, 25))

        self.horizontalLayout_17.addWidget(self.about_btn)


        self.verticalLayout_3.addWidget(self.frame_32)

        self.frame_30 = QFrame(self.frame_4)
        self.frame_30.setObjectName(u"frame_30")
        self.frame_30.setMaximumSize(QSize(16777215, 75))
        self.frame_30.setFrameShape(QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_16 = QHBoxLayout(self.frame_30)
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.frame_31 = QFrame(self.frame_30)
        self.frame_31.setObjectName(u"frame_31")
        self.frame_31.setMaximumSize(QSize(50, 50))
        self.frame_31.setStyleSheet(u"background-image:url(:/resource/icons/icons8-github-50.png)")
        self.frame_31.setFrameShape(QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_16.addWidget(self.frame_31)

        self.feedback_btn = QPushButton(self.frame_30)
        self.feedback_btn.setObjectName(u"feedback_btn")
        self.feedback_btn.setMinimumSize(QSize(0, 50))
        self.feedback_btn.setMaximumSize(QSize(16777215, 50))
        self.feedback_btn.setFont(font4)
        self.feedback_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.feedback_btn.setStyleSheet(u"color: #000000;")
        self.feedback_btn.setIconSize(QSize(0, 0))

        self.horizontalLayout_16.addWidget(self.feedback_btn)


        self.verticalLayout_3.addWidget(self.frame_30)


        self.verticalLayout_2.addWidget(self.frame_4)


        self.horizontalLayout.addWidget(self.side_menu)

        self.main_body = QFrame(self.frame_2)
        self.main_body.setObjectName(u"main_body")
        sizePolicy1.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy1)
        self.main_body.setFrameShape(QFrame.StyledPanel)
        self.main_body.setFrameShadow(QFrame.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.main_body)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.main_page = QStackedWidget(self.main_body)
        self.main_page.setObjectName(u"main_page")
        self.analyse_page = QWidget()
        self.analyse_page.setObjectName(u"analyse_page")
        self.verticalLayout_5 = QVBoxLayout(self.analyse_page)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.header_analyse = QFrame(self.analyse_page)
        self.header_analyse.setObjectName(u"header_analyse")
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Maximum)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.header_analyse.sizePolicy().hasHeightForWidth())
        self.header_analyse.setSizePolicy(sizePolicy4)
        self.header_analyse.setMinimumSize(QSize(0, 90))
        self.header_analyse.setMaximumSize(QSize(16777215, 90))
        self.header_analyse.setStyleSheet(u"background-color: #F5F5F5; border-radius: 10px;  ")
        self.header_analyse.setFrameShape(QFrame.StyledPanel)
        self.header_analyse.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_15 = QHBoxLayout(self.header_analyse)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.frame_27 = QFrame(self.header_analyse)
        self.frame_27.setObjectName(u"frame_27")
        self.frame_27.setMinimumSize(QSize(450, 0))
        self.frame_27.setFrameShape(QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QFrame.Raised)
        self.get_stat = QPushButton(self.frame_27)
        self.get_stat.setObjectName(u"get_stat")
        self.get_stat.setGeometry(QRect(270, 20, 151, 41))
        self.get_stat.setMaximumSize(QSize(151, 41))
        font5 = QFont()
        font5.setBold(False)
        font5.setItalic(False)
        self.get_stat.setFont(font5)
        self.get_stat.setCursor(QCursor(Qt.PointingHandCursor))
        self.get_stat.setLayoutDirection(Qt.LeftToRight)
        self.get_stat.setAutoFillBackground(False)
        self.get_stat.setStyleSheet(u"background-color: #43A047; color: black; border-radius: 10px")
        self.label_6 = QLabel(self.frame_27)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 20, 231, 41))
        font6 = QFont()
        font6.setPointSize(15)
        font6.setBold(True)
        self.label_6.setFont(font6)
        self.label_6.setLayoutDirection(Qt.RightToLeft)
        self.label_6.setStyleSheet(u"color: #000000; border: 0px solid")

        self.horizontalLayout_15.addWidget(self.frame_27)

        self.frame_28 = QFrame(self.header_analyse)
        self.frame_28.setObjectName(u"frame_28")
        sizePolicy3.setHeightForWidth(self.frame_28.sizePolicy().hasHeightForWidth())
        self.frame_28.setSizePolicy(sizePolicy3)
        self.frame_28.setFrameShape(QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_20 = QHBoxLayout(self.frame_28)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName(u"horizontalLayout_20")
        self.horizontalLayout_20.setContentsMargins(9, -1, 0, -1)
        self.frame_38 = QFrame(self.frame_28)
        self.frame_38.setObjectName(u"frame_38")
        self.frame_38.setMaximumSize(QSize(16777215, 16777215))
        self.frame_38.setFrameShape(QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_21 = QHBoxLayout(self.frame_38)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName(u"horizontalLayout_21")
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.dateEdit = QDateEdit(self.frame_38)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setMinimumSize(QSize(0, 30))
        self.dateEdit.setFont(font1)
        self.dateEdit.setStyleSheet(u"color: black; background-color: #E2DCDC;")
        self.dateEdit.setMinimumDate(QDate(2022, 3, 1))
        self.dateEdit.setCalendarPopup(True)

        self.horizontalLayout_21.addWidget(self.dateEdit)

        self.start_date_label_2 = QLabel(self.frame_38)
        self.start_date_label_2.setObjectName(u"start_date_label_2")
        self.start_date_label_2.setMaximumSize(QSize(20, 16777215))
        self.start_date_label_2.setFont(font2)
        self.start_date_label_2.setStyleSheet(u"color: black;")
        self.start_date_label_2.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_21.addWidget(self.start_date_label_2)

        self.dateEdit_2 = QDateEdit(self.frame_38)
        self.dateEdit_2.setObjectName(u"dateEdit_2")
        self.dateEdit_2.setMinimumSize(QSize(0, 30))
        self.dateEdit_2.setFont(font1)
        self.dateEdit_2.setStyleSheet(u"color: black; background-color: #E2DCDC;")
        self.dateEdit_2.setDateTime(QDateTime(QDate(2022, 3, 1), QTime(0, 0, 0)))
        self.dateEdit_2.setMinimumDate(QDate(2022, 3, 1))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setCurrentSectionIndex(0)

        self.horizontalLayout_21.addWidget(self.dateEdit_2)


        self.horizontalLayout_20.addWidget(self.frame_38)

        self.start_date_btn = QPushButton(self.frame_28)
        self.start_date_btn.setObjectName(u"start_date_btn")
        self.start_date_btn.setMinimumSize(QSize(50, 50))
        self.start_date_btn.setMaximumSize(QSize(50, 50))
        self.start_date_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.start_date_btn.setStyleSheet(u"background-image:url(:/resource/icons/icons8-\u0445\u0440\u043e\u043d\u043e\u043b\u043e\u0433\u0438\u044f-\u043d\u0435\u0434\u0435\u043b\u044f-50.png)")

        self.horizontalLayout_20.addWidget(self.start_date_btn)


        self.horizontalLayout_15.addWidget(self.frame_28)

        self.frame_29 = QFrame(self.header_analyse)
        self.frame_29.setObjectName(u"frame_29")
        self.frame_29.setMaximumSize(QSize(100, 16777215))
        self.frame_29.setFrameShape(QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QFrame.Raised)
        self.download_btn = QPushButton(self.frame_29)
        self.download_btn.setObjectName(u"download_btn")
        self.download_btn.setGeometry(QRect(20, 10, 60, 50))
        self.download_btn.setMinimumSize(QSize(60, 50))
        self.download_btn.setMaximumSize(QSize(60, 50))
        self.download_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.download_btn.setStyleSheet(u"background-image:url(:/resource/icons/icons8-\u044d\u043a\u0441\u043f\u043e\u0440\u0442-pdf-50.png)")

        self.horizontalLayout_15.addWidget(self.frame_29)


        self.verticalLayout_5.addWidget(self.header_analyse)

        self.scrollArea = QScrollArea(self.analyse_page)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 654, 1618))
        self.verticalLayout_6 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.scroll_frame = QFrame(self.scrollAreaWidgetContents)
        self.scroll_frame.setObjectName(u"scroll_frame")
        self.scroll_frame.setMinimumSize(QSize(0, 1600))
        self.scroll_frame.setStyleSheet(u"background-color: #F5F5F5; border-radius: 10px;")
        self.scroll_frame.setFrameShape(QFrame.StyledPanel)
        self.scroll_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.scroll_frame)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.frame_7 = QFrame(self.scroll_frame)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setMinimumSize(QSize(0, 150))
        self.frame_7.setMaximumSize(QSize(16777215, 150))
        self.frame_7.setStyleSheet(u"background-color: #F5F5F5; border-radius: 10px; border: 0px;")
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame_7)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 291, 21))
        font7 = QFont()
        font7.setPointSize(14)
        self.label.setFont(font7)
        self.label.setStyleSheet(u"color: black; border: 0px")
        self.label_13 = QLabel(self.frame_7)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 70, 401, 51))
        self.label_13.setFont(font7)
        self.label_13.setStyleSheet(u"color: black; border: 0px")
        self.all_views = QLabel(self.frame_7)
        self.all_views.setObjectName(u"all_views")
        self.all_views.setGeometry(QRect(180, 20, 431, 21))
        sizePolicy1.setHeightForWidth(self.all_views.sizePolicy().hasHeightForWidth())
        self.all_views.setSizePolicy(sizePolicy1)
        self.all_views.setFont(font)
        self.all_views.setStyleSheet(u"color: black;border: 0px")
        self.all_unique_views = QLabel(self.frame_7)
        self.all_unique_views.setObjectName(u"all_unique_views")
        self.all_unique_views.setGeometry(QRect(290, 85, 351, 21))
        self.all_unique_views.setFont(font)
        self.all_unique_views.setStyleSheet(u"color: black; border: 0px")

        self.verticalLayout_7.addWidget(self.frame_7)

        self.frame_5 = QFrame(self.scroll_frame)
        self.frame_5.setObjectName(u"frame_5")
        sizePolicy3.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy3)
        self.frame_5.setMaximumSize(QSize(16777215, 16777215))
        self.frame_5.setStyleSheet(u"background-color: #F5F5F5; border-radius: 10px;")
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.frame_8 = QFrame(self.frame_5)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setStyleSheet(u"border: 0px")
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.verticalLayout_8 = QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.label_7 = QLabel(self.frame_8)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setMaximumSize(QSize(16777215, 20))
        self.label_7.setFont(font4)
        self.label_7.setStyleSheet(u"color: #000000; border: 0px")

        self.verticalLayout_8.addWidget(self.label_7)

        self.MplWidget = MplWidget(self.frame_8)
        self.MplWidget.setObjectName(u"MplWidget")
        sizePolicy3.setHeightForWidth(self.MplWidget.sizePolicy().hasHeightForWidth())
        self.MplWidget.setSizePolicy(sizePolicy3)
        self.MplWidget.setMaximumSize(QSize(522, 600))
        self.MplWidget.setStyleSheet(u"background-color: #E2DCDC;")

        self.verticalLayout_8.addWidget(self.MplWidget)


        self.horizontalLayout_5.addWidget(self.frame_8)

        self.frame_9 = QFrame(self.frame_5)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setStyleSheet(u"border: 0px")
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.verticalLayout_9 = QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.label_9 = QLabel(self.frame_9)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setMaximumSize(QSize(16777215, 20))
        self.label_9.setFont(font4)
        self.label_9.setStyleSheet(u"color: #000000; border: 0px")

        self.verticalLayout_9.addWidget(self.label_9)

        self.MplWidget_2 = MplWidget(self.frame_9)
        self.MplWidget_2.setObjectName(u"MplWidget_2")
        sizePolicy3.setHeightForWidth(self.MplWidget_2.sizePolicy().hasHeightForWidth())
        self.MplWidget_2.setSizePolicy(sizePolicy3)
        self.MplWidget_2.setMaximumSize(QSize(522, 600))
        self.MplWidget_2.setStyleSheet(u"background-color: #E2DCDC; ")

        self.verticalLayout_9.addWidget(self.MplWidget_2)


        self.horizontalLayout_5.addWidget(self.frame_9)


        self.verticalLayout_7.addWidget(self.frame_5)

        self.frame_6 = QFrame(self.scroll_frame)
        self.frame_6.setObjectName(u"frame_6")
        sizePolicy1.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy1)
        self.frame_6.setStyleSheet(u"background-color: #F5F5F5; border-radius: 10px;")
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_6 = QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.frame_11 = QFrame(self.frame_6)
        self.frame_11.setObjectName(u"frame_11")
        sizePolicy1.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy1)
        self.frame_11.setMaximumSize(QSize(16777215, 16777215))
        self.frame_11.setStyleSheet(u"border: 0px")
        self.frame_11.setFrameShape(QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_7 = QHBoxLayout(self.frame_11)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(-1, -1, 9, -1)
        self.frame_10 = QFrame(self.frame_11)
        self.frame_10.setObjectName(u"frame_10")
        sizePolicy1.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy1)
        self.frame_10.setStyleSheet(u"border: 0px")
        self.frame_10.setFrameShape(QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.verticalLayout_10 = QVBoxLayout(self.frame_10)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, -1, -1, -1)
        self.label_8 = QLabel(self.frame_10)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setMaximumSize(QSize(16777215, 20))
        self.label_8.setFont(font4)
        self.label_8.setStyleSheet(u"color: #000000;")

        self.verticalLayout_10.addWidget(self.label_8)

        self.MplWidget_3 = MplDiagramma(self.frame_10)
        self.MplWidget_3.setObjectName(u"MplWidget_3")
        sizePolicy1.setHeightForWidth(self.MplWidget_3.sizePolicy().hasHeightForWidth())
        self.MplWidget_3.setSizePolicy(sizePolicy1)
        self.MplWidget_3.setMaximumSize(QSize(522, 600))
        self.MplWidget_3.setStyleSheet(u"background-color: #E2DCDC;")

        self.verticalLayout_10.addWidget(self.MplWidget_3)


        self.horizontalLayout_7.addWidget(self.frame_10)

        self.frame_12 = QFrame(self.frame_11)
        self.frame_12.setObjectName(u"frame_12")
        sizePolicy1.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy1)
        self.frame_12.setMaximumSize(QSize(16777215, 16777215))
        self.frame_12.setStyleSheet(u"border: 0px")
        self.frame_12.setFrameShape(QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.verticalLayout_11 = QVBoxLayout(self.frame_12)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(9, -1, 0, -1)
        self.label_10 = QLabel(self.frame_12)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setMaximumSize(QSize(16777215, 20))
        self.label_10.setFont(font4)
        self.label_10.setStyleSheet(u"color: #000000;")

        self.verticalLayout_11.addWidget(self.label_10)

        self.MplWidget_4 = MplDiagramma(self.frame_12)
        self.MplWidget_4.setObjectName(u"MplWidget_4")
        sizePolicy1.setHeightForWidth(self.MplWidget_4.sizePolicy().hasHeightForWidth())
        self.MplWidget_4.setSizePolicy(sizePolicy1)
        self.MplWidget_4.setMaximumSize(QSize(522, 600))
        self.MplWidget_4.setStyleSheet(u"background-color: #E2DCDC;")

        self.verticalLayout_11.addWidget(self.MplWidget_4)


        self.horizontalLayout_7.addWidget(self.frame_12)


        self.horizontalLayout_6.addWidget(self.frame_11)


        self.verticalLayout_7.addWidget(self.frame_6)

        self.frame_13 = QFrame(self.scroll_frame)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setStyleSheet(u"background-color: #F5F5F5; border-radius: 10px;")
        self.frame_13.setFrameShape(QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_9 = QHBoxLayout(self.frame_13)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.frame_14 = QFrame(self.frame_13)
        self.frame_14.setObjectName(u"frame_14")
        sizePolicy1.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy1)
        self.frame_14.setMaximumSize(QSize(16777215, 16777215))
        self.frame_14.setStyleSheet(u"border: 0px")
        self.frame_14.setFrameShape(QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_8 = QHBoxLayout(self.frame_14)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(-1, -1, 9, -1)
        self.frame_15 = QFrame(self.frame_14)
        self.frame_15.setObjectName(u"frame_15")
        self.frame_15.setFrameShape(QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QFrame.Raised)
        self.verticalLayout_12 = QVBoxLayout(self.frame_15)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, -1, -1, -1)
        self.label_11 = QLabel(self.frame_15)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setMaximumSize(QSize(16777215, 20))
        self.label_11.setFont(font4)
        self.label_11.setStyleSheet(u"color: #000000;")

        self.verticalLayout_12.addWidget(self.label_11)

        self.MplWidget_5 = MplDiagramma(self.frame_15)
        self.MplWidget_5.setObjectName(u"MplWidget_5")
        sizePolicy3.setHeightForWidth(self.MplWidget_5.sizePolicy().hasHeightForWidth())
        self.MplWidget_5.setSizePolicy(sizePolicy3)
        self.MplWidget_5.setMaximumSize(QSize(522, 600))
        self.MplWidget_5.setLayoutDirection(Qt.LeftToRight)
        self.MplWidget_5.setStyleSheet(u"background-color: #E2DCDC;")

        self.verticalLayout_12.addWidget(self.MplWidget_5)


        self.horizontalLayout_8.addWidget(self.frame_15)

        self.frame_16 = QFrame(self.frame_14)
        self.frame_16.setObjectName(u"frame_16")
        sizePolicy3.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy3)
        self.frame_16.setMaximumSize(QSize(16777215, 16777215))
        self.frame_16.setFrameShape(QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QFrame.Raised)
        self.verticalLayout_13 = QVBoxLayout(self.frame_16)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(9, -1, 0, -1)
        self.label_12 = QLabel(self.frame_16)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setMaximumSize(QSize(16777215, 20))
        self.label_12.setFont(font4)
        self.label_12.setStyleSheet(u"color: #000000;")

        self.verticalLayout_13.addWidget(self.label_12)

        self.MplWidget_6 = MplDiagramma(self.frame_16)
        self.MplWidget_6.setObjectName(u"MplWidget_6")
        sizePolicy3.setHeightForWidth(self.MplWidget_6.sizePolicy().hasHeightForWidth())
        self.MplWidget_6.setSizePolicy(sizePolicy3)
        self.MplWidget_6.setMaximumSize(QSize(522, 600))
        self.MplWidget_6.setStyleSheet(u"background-color: #E2DCDC;")

        self.verticalLayout_13.addWidget(self.MplWidget_6)


        self.horizontalLayout_8.addWidget(self.frame_16)


        self.horizontalLayout_9.addWidget(self.frame_14)


        self.verticalLayout_7.addWidget(self.frame_13)


        self.verticalLayout_6.addWidget(self.scroll_frame)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_5.addWidget(self.scrollArea)

        self.main_page.addWidget(self.analyse_page)
        self.getstat_page = QWidget()
        self.getstat_page.setObjectName(u"getstat_page")
        self.verticalLayout_17 = QVBoxLayout(self.getstat_page)
        self.verticalLayout_17.setObjectName(u"verticalLayout_17")
        self.frame_21 = QFrame(self.getstat_page)
        self.frame_21.setObjectName(u"frame_21")
        self.frame_21.setStyleSheet(u"background-color: white; border-radius: 20px;")
        self.frame_21.setFrameShape(QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_13 = QHBoxLayout(self.frame_21)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.frame_22 = QFrame(self.frame_21)
        self.frame_22.setObjectName(u"frame_22")
        self.frame_22.setStyleSheet(u"background-color: #E2DCDC; background-image: url(:/resource/icons/data-image.png); ")
        self.frame_22.setFrameShape(QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QFrame.Raised)
        self.frame_22.setLineWidth(1)
        self.frame_22.setMidLineWidth(0)
        self.label_15 = QLabel(self.frame_22)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(170, 100, 411, 141))
        font8 = QFont()
        font8.setPointSize(21)
        font8.setBold(False)
        self.label_15.setFont(font8)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setStyleSheet(u"color: black;")
        self.label_15.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.label_15.setWordWrap(True)
        self.label_14 = QLabel(self.frame_22)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(150, 40, 441, 41))
        font9 = QFont()
        font9.setPointSize(23)
        font9.setBold(True)
        self.label_14.setFont(font9)
        self.label_14.setStyleSheet(u"color: black;")

        self.horizontalLayout_13.addWidget(self.frame_22)

        self.frame_23 = QFrame(self.frame_21)
        self.frame_23.setObjectName(u"frame_23")
        self.frame_23.setMaximumSize(QSize(420, 16777215))
        font10 = QFont()
        font10.setPointSize(15)
        self.frame_23.setFont(font10)
        self.frame_23.setStyleSheet(u"background-color: #E0E0E0; border-radius: 20px;")
        self.frame_23.setFrameShape(QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QFrame.Raised)
        self.frame_24 = QFrame(self.frame_23)
        self.frame_24.setObjectName(u"frame_24")
        self.frame_24.setGeometry(QRect(0, 160, 400, 235))
        sizePolicy5 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Preferred)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.frame_24.sizePolicy().hasHeightForWidth())
        self.frame_24.setSizePolicy(sizePolicy5)
        self.frame_24.setMinimumSize(QSize(400, 0))
        self.frame_24.setAutoFillBackground(False)
        self.frame_24.setFrameShape(QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_14 = QHBoxLayout(self.frame_24)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.frame_25 = QFrame(self.frame_24)
        self.frame_25.setObjectName(u"frame_25")
        self.frame_25.setMaximumSize(QSize(135, 16777215))
        self.frame_25.setFrameShape(QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QFrame.Raised)
        self.verticalLayout_18 = QVBoxLayout(self.frame_25)
        self.verticalLayout_18.setSpacing(15)
        self.verticalLayout_18.setObjectName(u"verticalLayout_18")
        self.server_label = QLabel(self.frame_25)
        self.server_label.setObjectName(u"server_label")
        font11 = QFont()
        font11.setPointSize(20)
        self.server_label.setFont(font11)
        self.server_label.setStyleSheet(u"color: black;")

        self.verticalLayout_18.addWidget(self.server_label)

        self.user_label = QLabel(self.frame_25)
        self.user_label.setObjectName(u"user_label")
        self.user_label.setFont(font11)
        self.user_label.setStyleSheet(u"color: #000000;")

        self.verticalLayout_18.addWidget(self.user_label)

        self.table_label = QLabel(self.frame_25)
        self.table_label.setObjectName(u"table_label")
        self.table_label.setFont(font11)
        self.table_label.setStyleSheet(u"color: #000000;")

        self.verticalLayout_18.addWidget(self.table_label)

        self.table_label_2 = QLabel(self.frame_25)
        self.table_label_2.setObjectName(u"table_label_2")
        self.table_label_2.setFont(font11)
        self.table_label_2.setStyleSheet(u"color: #000000;")

        self.verticalLayout_18.addWidget(self.table_label_2)


        self.horizontalLayout_14.addWidget(self.frame_25)

        self.frame_26 = QFrame(self.frame_24)
        self.frame_26.setObjectName(u"frame_26")
        self.frame_26.setFrameShape(QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QFrame.Raised)
        self.server_lineEdit = QLineEdit(self.frame_26)
        self.server_lineEdit.setObjectName(u"server_lineEdit")
        self.server_lineEdit.setGeometry(QRect(0, 20, 241, 25))
        self.server_lineEdit.setMinimumSize(QSize(0, 25))
        self.server_lineEdit.setStyleSheet(u"background-color: #e5e3e3; border: 1px solid black; color: black;")
        self.user_lineEdit = QLineEdit(self.frame_26)
        self.user_lineEdit.setObjectName(u"user_lineEdit")
        self.user_lineEdit.setGeometry(QRect(0, 70, 241, 25))
        self.user_lineEdit.setMinimumSize(QSize(0, 25))
        self.user_lineEdit.setStyleSheet(u"background-color: #e5e3e3; border: 1px solid black; color: black;")
        self.table_lineEdit = QLineEdit(self.frame_26)
        self.table_lineEdit.setObjectName(u"table_lineEdit")
        self.table_lineEdit.setGeometry(QRect(0, 125, 241, 25))
        self.table_lineEdit.setMinimumSize(QSize(0, 25))
        self.table_lineEdit.setStyleSheet(u"background-color: #e5e3e3; border: 1px solid black; color: black;")
        self.password_lineEdit = QLineEdit(self.frame_26)
        self.password_lineEdit.setObjectName(u"password_lineEdit")
        self.password_lineEdit.setGeometry(QRect(0, 175, 241, 25))
        self.password_lineEdit.setMinimumSize(QSize(0, 25))
        self.password_lineEdit.setStyleSheet(u"background-color: #e5e3e3; border: 1px solid black; color: black;")

        self.horizontalLayout_14.addWidget(self.frame_26)

        self.connectDB_btn = QPushButton(self.frame_23)
        self.connectDB_btn.setObjectName(u"connectDB_btn")
        self.connectDB_btn.setGeometry(QRect(10, 410, 161, 41))
        font12 = QFont()
        font12.setPointSize(16)
        self.connectDB_btn.setFont(font12)
        self.connectDB_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.connectDB_btn.setStyleSheet(u"color: black; background-color: #43A047; border-radius: 20px;")

        self.horizontalLayout_13.addWidget(self.frame_23)


        self.verticalLayout_17.addWidget(self.frame_21)

        self.main_page.addWidget(self.getstat_page)
        self.connect_page = QCustomSlideMenu()
        self.connect_page.setObjectName(u"connect_page")
        self.main_page.addWidget(self.connect_page)
        self.about_page = QWidget()
        self.about_page.setObjectName(u"about_page")
        self.verticalLayout_15 = QVBoxLayout(self.about_page)
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.frame_20 = QFrame(self.about_page)
        self.frame_20.setObjectName(u"frame_20")
        sizePolicy1.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy1)
        self.frame_20.setFrameShape(QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QFrame.Raised)
        self.verticalLayout_16 = QVBoxLayout(self.frame_20)
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.verticalLayout_16.setContentsMargins(0, -1, -1, -1)
        self.label_3 = QLabel(self.frame_20)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setMaximumSize(QSize(16777215, 70))
        font13 = QFont()
        font13.setPointSize(17)
        font13.setBold(True)
        self.label_3.setFont(font13)
        self.label_3.setStyleSheet(u"color: black;")

        self.verticalLayout_16.addWidget(self.label_3)

        self.frame_39 = QFrame(self.frame_20)
        self.frame_39.setObjectName(u"frame_39")
        self.frame_39.setFrameShape(QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QFrame.Raised)
        self.frame_40 = QFrame(self.frame_39)
        self.frame_40.setObjectName(u"frame_40")
        self.frame_40.setGeometry(QRect(20, 10, 50, 50))
        self.frame_40.setMinimumSize(QSize(50, 50))
        self.frame_40.setMaximumSize(QSize(50, 50))
        self.frame_40.setStyleSheet(u"background-image:url(:/resource/icons/icons8-\u0433\u043b\u0430\u0432\u043d\u0430\u044f-\u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430-50.png)")
        self.frame_40.setFrameShape(QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.frame_39)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(80, 10, 1136, 50))
        self.label_4.setMaximumSize(QSize(16777215, 50))
        self.label_4.setFont(font13)
        self.label_4.setStyleSheet(u"color: black;")
        self.frame_41 = QFrame(self.frame_39)
        self.frame_41.setObjectName(u"frame_41")
        self.frame_41.setGeometry(QRect(20, 70, 50, 50))
        self.frame_41.setMinimumSize(QSize(50, 50))
        self.frame_41.setMaximumSize(QSize(50, 50))
        self.frame_41.setStyleSheet(u"background-image:url(:/resource/icons/icons8-\u0434\u0438\u0430\u0433\u0440\u0430\u043c\u043c\u0430-\u0441-\u043e\u0431\u043b\u0430\u0441\u0442\u044f\u043c\u0438-50.png)")
        self.frame_41.setFrameShape(QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QFrame.Raised)
        self.label_5 = QLabel(self.frame_39)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(80, 70, 1136, 50))
        self.label_5.setMaximumSize(QSize(16777215, 50))
        self.label_5.setFont(font13)
        self.label_5.setStyleSheet(u"color: black;")
        self.frame_42 = QFrame(self.frame_39)
        self.frame_42.setObjectName(u"frame_42")
        self.frame_42.setGeometry(QRect(20, 130, 50, 50))
        self.frame_42.setMinimumSize(QSize(50, 50))
        self.frame_42.setMaximumSize(QSize(50, 50))
        self.frame_42.setStyleSheet(u"background-image:url(:/resource/icons/icons8-\u0445\u0440\u043e\u043d\u043e\u043b\u043e\u0433\u0438\u044f-\u043d\u0435\u0434\u0435\u043b\u044f-50.png)")
        self.frame_42.setFrameShape(QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QFrame.Raised)
        self.label_16 = QLabel(self.frame_39)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(80, 130, 1136, 60))
        self.label_16.setMinimumSize(QSize(0, 60))
        self.label_16.setMaximumSize(QSize(16777215, 60))
        self.label_16.setFont(font13)
        self.label_16.setStyleSheet(u"color: black;")
        self.label_16.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_16.setWordWrap(True)
        self.frame_43 = QFrame(self.frame_39)
        self.frame_43.setObjectName(u"frame_43")
        self.frame_43.setGeometry(QRect(20, 190, 50, 50))
        self.frame_43.setMinimumSize(QSize(50, 50))
        self.frame_43.setMaximumSize(QSize(50, 50))
        self.frame_43.setStyleSheet(u"background-image:url(:/resource/icons/icons8-\u044d\u043a\u0441\u043f\u043e\u0440\u0442-pdf-50.png)")
        self.frame_43.setFrameShape(QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QFrame.Raised)
        self.label_17 = QLabel(self.frame_39)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(80, 190, 1136, 50))
        self.label_17.setMaximumSize(QSize(16777215, 50))
        self.label_17.setFont(font13)
        self.label_17.setStyleSheet(u"color: black;")

        self.verticalLayout_16.addWidget(self.frame_39)


        self.verticalLayout_15.addWidget(self.frame_20)

        self.main_page.addWidget(self.about_page)
        self.feedback_page = QWidget()
        self.feedback_page.setObjectName(u"feedback_page")
        self.horizontalLayout_10 = QHBoxLayout(self.feedback_page)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.frame_17 = QFrame(self.feedback_page)
        self.frame_17.setObjectName(u"frame_17")
        self.frame_17.setFrameShape(QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QFrame.Raised)
        self.verticalLayout_14 = QVBoxLayout(self.frame_17)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.frame_19 = QFrame(self.frame_17)
        self.frame_19.setObjectName(u"frame_19")
        sizePolicy1.setHeightForWidth(self.frame_19.sizePolicy().hasHeightForWidth())
        self.frame_19.setSizePolicy(sizePolicy1)
        self.frame_19.setMinimumSize(QSize(0, 120))
        self.frame_19.setMaximumSize(QSize(16777215, 120))
        self.frame_19.setFrameShape(QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_11 = QHBoxLayout(self.frame_19)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.label_2 = QLabel(self.frame_19)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font13)
        self.label_2.setStyleSheet(u"color: black")

        self.horizontalLayout_11.addWidget(self.label_2)


        self.verticalLayout_14.addWidget(self.frame_19)

        self.frame_18 = QFrame(self.frame_17)
        self.frame_18.setObjectName(u"frame_18")
        sizePolicy1.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy1)
        self.frame_18.setFrameShape(QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_12 = QHBoxLayout(self.frame_18)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.horizontalLayout_12.setContentsMargins(-1, -1, -1, 300)
        self.vk_btn = QPushButton(self.frame_18)
        self.vk_btn.setObjectName(u"vk_btn")
        self.vk_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon4 = QIcon()
        icon4.addFile(u":/resource/icons/icons8-vk-\u0432-\u043a\u0440\u0443\u0433\u0435-100.png", QSize(), QIcon.Normal, QIcon.Off)
        self.vk_btn.setIcon(icon4)
        self.vk_btn.setIconSize(QSize(150, 150))

        self.horizontalLayout_12.addWidget(self.vk_btn)

        self.github_btn = QPushButton(self.frame_18)
        self.github_btn.setObjectName(u"github_btn")
        self.github_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon5 = QIcon()
        icon5.addFile(u":/resource/icons/icons8-github-100.png", QSize(), QIcon.Normal, QIcon.Off)
        self.github_btn.setIcon(icon5)
        self.github_btn.setIconSize(QSize(150, 150))

        self.horizontalLayout_12.addWidget(self.github_btn)

        self.tg_btn = QPushButton(self.frame_18)
        self.tg_btn.setObjectName(u"tg_btn")
        self.tg_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon6 = QIcon()
        icon6.addFile(u":/resource/icons/icons8-\u0442\u0435\u043b\u0435\u0433\u0440\u0430\u043c\u043c\u0430-app-100.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tg_btn.setIcon(icon6)
        self.tg_btn.setIconSize(QSize(150, 150))

        self.horizontalLayout_12.addWidget(self.tg_btn)

        self.mail_btn = QPushButton(self.frame_18)
        self.mail_btn.setObjectName(u"mail_btn")
        self.mail_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon7 = QIcon()
        icon7.addFile(u":/resource/icons/icons8-\u043f\u043e\u0447\u0442\u0430-100.png", QSize(), QIcon.Normal, QIcon.Off)
        self.mail_btn.setIcon(icon7)
        self.mail_btn.setIconSize(QSize(150, 150))

        self.horizontalLayout_12.addWidget(self.mail_btn)


        self.verticalLayout_14.addWidget(self.frame_18)


        self.horizontalLayout_10.addWidget(self.frame_17)

        self.main_page.addWidget(self.feedback_page)

        self.verticalLayout_4.addWidget(self.main_page)


        self.horizontalLayout.addWidget(self.main_body)


        self.verticalLayout.addWidget(self.frame_2)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.main_page.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"GetStat", None))
        self.menu_btn.setText("")
        self.getstat.setText(QCoreApplication.translate("MainWindow", u"GetStat", None))
        self.getstat_btn.setText(QCoreApplication.translate("MainWindow", u"GetStat", None))
        self.analyse_btn.setText(QCoreApplication.translate("MainWindow", u"Analyse", None))
        self.about_btn.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.feedback_btn.setText(QCoreApplication.translate("MainWindow", u"Feedback", None))
        self.get_stat.setText(QCoreApplication.translate("MainWindow", u"GET", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u043f\u0440\u043e\u0441\u0438\u0442\u044c \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0443:", None))
        self.start_date_label_2.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.start_date_btn.setText("")
        self.download_btn.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0441\u0435\u0433\u043e \u043f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u0439:", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0441\u0435\u0433\u043e \u0443\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0445 \u043f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u0439:", None))
        self.all_views.setText("")
        self.all_unique_views.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u0439 \u0432 \u0434\u0435\u043d\u044c:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0445 \u043f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u0439 \u0432 \u0434\u0435\u043d\u044c:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u" \u0411\u0440\u0430\u0443\u0437\u0435\u0440\u044b:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u0440\u0430\u043d\u044b:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0430:", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u0413\u043e\u0440\u043e\u0434\u0430:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043b\u044f \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0438 \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0438\u0442\u0435\u0441\u044c \u043a \u0431\u0430\u0437\u0435 \u0434\u0430\u043d\u043d\u044b\u0445, \u0445\u0440\u0430\u043d\u044f\u0449\u0435\u0439 \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044e \u043e \u043f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u044f\u0445", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0440\u043e \u043f\u043e\u0436\u0430\u043b\u043e\u0432\u0430\u0442\u044c \u0432 GetStat ", None))
        self.server_label.setText(QCoreApplication.translate("MainWindow", u"Server", None))
        self.user_label.setText(QCoreApplication.translate("MainWindow", u"User", None))
        self.table_label.setText(QCoreApplication.translate("MainWindow", u"Table", None))
        self.table_label_2.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.connectDB_btn.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0436\u043c\u0438\u0442\u0435:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043b\u044f \u043f\u0435\u0440\u0435\u0445\u043e\u0434\u0430 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443 \u043f\u0440\u0438\u0432\u0435\u0442\u0441\u0442\u0432\u0438\u044f \u0438 \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u044f \u043a \u0411\u0414", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043b\u044f \u043f\u0435\u0440\u0435\u0445\u043e\u0434\u0430 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443 \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0438", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043b\u044f \u0432\u044b\u0431\u043e\u0440\u0430 \u043f\u0435\u0440\u0438\u043e\u0434\u0430 \u0437\u0430 \u043a\u043e\u0442\u043e\u0440\u044b\u0439 \u043d\u0443\u0436\u043d\u043e \u043f\u043e\u043b\u0443\u0447\u0438\u0442\u044c \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0443. \u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u0431\u0443\u0434\u0435\u0442 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c\u0441\u044f                     \u0437\u0430 \u0432\u0441\u0435 \u0432\u0440\u0435\u043c\u044f, \u0435\u0441\u043b\u0438 \u0432\u0438\u0434\u0436\u0435\u0442 \u043d\u0435 \u0430\u043a\u0442\u0438\u0432\u0435\u043d", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043b\u044f \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438 \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0438 \u0432 \u0444\u043e\u0440\u043c\u0430\u0442\u0435 PDF", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 \u0441\u0435\u0442\u0438 \u0440\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u0447\u0438\u043a\u0430:", None))
        self.vk_btn.setText("")
        self.github_btn.setText("")
        self.tg_btn.setText("")
        self.mail_btn.setText("")
    # retranslateUi

